---
title: "cpt figures"
date: "`r Sys.Date()`"
output: html_document
vignette: >
  %\VignetteIndexEntry{Vignette cpt figures}
  %\VignetteEngine{knitr::knitr}
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(trackframe)
library(cpt)
attach(getNamespace("cpt")) # FIXME: when plot functions are exported
library(tinyplot)
data("cptfiguredata_tf")
tf <- cptfiguredata_tf
# FIXME
tf$y <- tf$y * (-1)

# tinytheme("minimal")
tinytheme("clean2")
# tinytheme()
```

### Fig  3

```{r}
tf3 <- tf[startsWith(tf$track_id, '3'), ]
```

#### multiple tracks

with `plot.trackframe()` method
```{r}
plot(tf3)
plot(tf3, direction = TRUE)
```


#### single track

```{r}
plot(select_id(tf3, "3a"))
```



### Fig 4

```{r}
tf4 <- tf[startsWith(tf$track_id, '4'), ]

cpt <- change_point_test(
  tf4,
  alpha = .01,
  n = 10000,
  q = 6
)

class(cpt)
```


```{r}
plot(cpt)
plot(cpt, direction = TRUE)

cpt4a <- select_id(cpt, "4a")
plot(cpt4a)
plot(cpt4a, direction = TRUE)
```

### Fig 5


```{r}
n <- 100
tf_4a <- tf[tf$track_id == '4a', ]
set.seed(2025)
p <- change_point_test_pvalue(
  # p = cpt:::change_point_test_pvalue_old(
  # gives different result due to different calculation order
  tf_4a,
  q_max = 10,
  n = n
)
```

```{r}
plot(p)
```



### Fig 6

```{r}
calculate_n_cp_by_q <- function(tf, q = seq_len(10), alpha = 0.01) {
  # tf <- tf[startsWith(tf$track_id, '4'), ]
  if (length(attr(tf, 'id')) != 1) {
    stop('only implemented for 1 id col')
  }
  do.call(
    rbind,
    lapply(seq_len(10), function(q) {
      cp <- change_point_test(
        tf,
        alpha = alpha,
        q = q
      )
      # cp <- do.call(rbind, lapply(seq_len(cp), function(i) cbind(cp, "track_id" = i)))
      df <- as.data.frame(rowsum(cp$sig, as.factor(cp[, attr(tf, 'id')])))
      names(df) <- 'n_cp'
      df$track_id <- rownames(df)
      rownames(df) <- NULL
      df$q <- q
      df
    })
  )
}

fig6_data <- calculate_n_cp_by_q(tf4)
```


```{r}
plot_n_cp_by_q(data = fig6_data, id_col = "track_id")
```


### Fig 7

```{r}
tf7 <- tf[startsWith(tf$track_id, '7'), ]
cp <- change_point_test(
  tf7,
  alpha = .05,
  q = 4
)

```


```{r}
plot(cp)
plot(cp, direction = TRUE)
```



### Fig 8


```{r}
n <- 100
tf_7a <- tf[tf$track_id == '7a', ]
set.seed(2025)
data <- tf_7a
p <- change_point_test_pvalue(
  #gives different result due to different calculation order
  # P = cpt:::change_point_test_pvalue_old(
  data,
  q_max = 6,
  n = n
)
```


```{r}
plot(p)
```


## Fig 9

```{r}
fig9_data <- calculate_n_cp_by_q(tf7, alpha = 0.05)
```


```{r}
plot_n_cp_by_q(fig9_data, id_col = "track_id")
```

