// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpparma_change_point_test_fit
arma::dvec rcpparma_change_point_test_fit(arma::dvec bx, arma::dvec by, int32_t q, int32_t N, double alpha);
RcppExport SEXP _changepointpermtest2009_rcpparma_change_point_test_fit(SEXP bxSEXP, SEXP bySEXP, SEXP qSEXP, SEXP NSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::dvec >::type bx(bxSEXP);
    Rcpp::traits::input_parameter< arma::dvec >::type by(bySEXP);
    Rcpp::traits::input_parameter< int32_t >::type q(qSEXP);
    Rcpp::traits::input_parameter< int32_t >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_change_point_test_fit(bx, by, q, N, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_change_point_test_pvalue
arma::mat rcpparma_change_point_test_pvalue(arma::dvec bx, arma::dvec by, int32_t q_max, int32_t N);
RcppExport SEXP _changepointpermtest2009_rcpparma_change_point_test_pvalue(SEXP bxSEXP, SEXP bySEXP, SEXP q_maxSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::dvec >::type bx(bxSEXP);
    Rcpp::traits::input_parameter< arma::dvec >::type by(bySEXP);
    Rcpp::traits::input_parameter< int32_t >::type q_max(q_maxSEXP);
    Rcpp::traits::input_parameter< int32_t >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_change_point_test_pvalue(bx, by, q_max, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_changepointpermtest2009_rcpparma_change_point_test_fit", (DL_FUNC) &_changepointpermtest2009_rcpparma_change_point_test_fit, 5},
    {"_changepointpermtest2009_rcpparma_change_point_test_pvalue", (DL_FUNC) &_changepointpermtest2009_rcpparma_change_point_test_pvalue, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_changepointpermtest2009(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
