# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_change_point_test_fit <- function(bx, by, q, N, alpha) {
    .Call(`_cpt_rcpparma_change_point_test_fit`, bx, by, q, N, alpha)
}

